export type ContentLibraryItem = {
  id: string;
  title: string;
  author_or_host: string | null;
  media_type: string;
  cefr_level?: string | null;
  external_url?: string | null;
  description?: string | null;
  duration_label?: string | null;
  genre_tag?: string | null;
  playlist_tag?: string | null;
  thumbnail_url?: string | null;
  sort_order?: number | null;
};

function justWatchUrl(query: string) {
  return `https://www.justwatch.com/us/search?q=${encodeURIComponent(query)}`;
}

function spotifySearchUrl(query: string) {
  return `https://open.spotify.com/search/${encodeURIComponent(query)}`;
}

const referenceContentItems: ContentLibraryItem[] = [
  {
    id: "ref-show-friends",
    title: "Friends",
    author_or_host: "TV Show",
    media_type: "show",
    cefr_level: "A2-B1",
    external_url: justWatchUrl("Friends"),
    genre_tag: "TV Show",
    thumbnail_url: "https://image.tmdb.org/t/p/w300/f496cm9enuEsZkSPzCwnTESEK5s.jpg",
    sort_order: 1,
  },
  {
    id: "ref-show-office",
    title: "The Office",
    author_or_host: "TV Show",
    media_type: "show",
    cefr_level: "B1-B2",
    external_url: justWatchUrl("The Office"),
    genre_tag: "TV Show",
    thumbnail_url: "https://image.tmdb.org/t/p/w300/7DJKHzAi83BmQrWLrYYOqcoKfhR.jpg",
    sort_order: 2,
  },
  {
    id: "ref-show-modern-family",
    title: "Modern Family",
    author_or_host: "TV Show",
    media_type: "show",
    cefr_level: "B1-B2",
    external_url: justWatchUrl("Modern Family"),
    genre_tag: "TV Show",
    thumbnail_url: "https://image.tmdb.org/t/p/w500/k5Qg5rgPoKdh3yTJJrLtyoyYGwC.jpg",
    sort_order: 3,
  },
  {
    id: "ref-show-ted-lasso",
    title: "Ted Lasso",
    author_or_host: "TV Show",
    media_type: "show",
    cefr_level: "B2",
    external_url: justWatchUrl("Ted Lasso"),
    genre_tag: "TV Show",
    thumbnail_url: "https://image.tmdb.org/t/p/w300/5fhZdwP1DVJ0FyVH6vrFdHwpXIn.jpg",
    sort_order: 4,
  },
  {
    id: "ref-show-brooklyn",
    title: "Brooklyn Nine-Nine",
    author_or_host: "TV Show",
    media_type: "show",
    cefr_level: "B1-B2",
    external_url: justWatchUrl("Brooklyn Nine-Nine"),
    genre_tag: "TV Show",
    thumbnail_url: "https://image.tmdb.org/t/p/w300/hgRMSOt7a1b8qyQR68vUixJPang.jpg",
    sort_order: 5,
  },
  {
    id: "ref-show-emily",
    title: "Emily in Paris",
    author_or_host: "TV Show",
    media_type: "show",
    cefr_level: "B1",
    external_url: justWatchUrl("Emily in Paris"),
    genre_tag: "TV Show",
    thumbnail_url: "https://image.tmdb.org/t/p/w500/c0bkO416OU7YGdOFktk45H8REgL.jpg",
    sort_order: 6,
  },
  {
    id: "ref-show-stranger",
    title: "Stranger Things",
    author_or_host: "TV Show",
    media_type: "show",
    cefr_level: "B2",
    external_url: justWatchUrl("Stranger Things"),
    genre_tag: "TV Show",
    thumbnail_url: "https://image.tmdb.org/t/p/w300/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    sort_order: 7,
  },
  {
    id: "ref-show-crown",
    title: "The Crown",
    author_or_host: "TV Show",
    media_type: "show",
    cefr_level: "C1",
    external_url: justWatchUrl("The Crown"),
    genre_tag: "TV Show",
    thumbnail_url: "https://image.tmdb.org/t/p/w300/1M876KPjulVwppEpldhdc8V4o68.jpg",
    sort_order: 8,
  },
  {
    id: "ref-movie-forrest",
    title: "Forrest Gump",
    author_or_host: "Movie",
    media_type: "movie",
    cefr_level: "B1",
    external_url: justWatchUrl("Forrest Gump"),
    genre_tag: "Movie",
    thumbnail_url: "https://image.tmdb.org/t/p/w300/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    sort_order: 1,
  },
  {
    id: "ref-movie-happyness",
    title: "Pursuit of Happyness",
    author_or_host: "Movie",
    media_type: "movie",
    cefr_level: "B1-B2",
    external_url: justWatchUrl("The Pursuit of Happyness"),
    genre_tag: "Movie",
    thumbnail_url: "https://image.tmdb.org/t/p/w500/lBYOKAMcxIvuk9s9hMuecB9dPBV.jpg",
    sort_order: 2,
  },
  {
    id: "ref-movie-prada",
    title: "The Devil Wears Prada",
    author_or_host: "Movie",
    media_type: "movie",
    cefr_level: "B2",
    external_url: justWatchUrl("The Devil Wears Prada"),
    genre_tag: "Movie",
    thumbnail_url: "https://image.tmdb.org/t/p/w500/8912AsVuS7Sj915apArUFbv6F9L.jpg",
    sort_order: 3,
  },
  {
    id: "ref-movie-inside-out",
    title: "Inside Out",
    author_or_host: "Movie",
    media_type: "movie",
    cefr_level: "A2-B1",
    external_url: justWatchUrl("Inside Out"),
    genre_tag: "Movie",
    thumbnail_url: "https://image.tmdb.org/t/p/w500/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg",
    sort_order: 4,
  },
  {
    id: "ref-movie-lala",
    title: "La La Land",
    author_or_host: "Movie",
    media_type: "movie",
    cefr_level: "B1-B2",
    external_url: justWatchUrl("La La Land"),
    genre_tag: "Movie",
    thumbnail_url: "https://image.tmdb.org/t/p/w300/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    sort_order: 5,
  },
  {
    id: "ref-movie-little-women",
    title: "Little Women",
    author_or_host: "Movie",
    media_type: "movie",
    cefr_level: "B2",
    external_url: justWatchUrl("Little Women"),
    genre_tag: "Movie",
    thumbnail_url: "https://image.tmdb.org/t/p/w500/yn5ihODtZ7ofn8pDYfxCmxh8AXI.jpg",
    sort_order: 6,
  },
  {
    id: "ref-movie-social",
    title: "The Social Network",
    author_or_host: "Movie",
    media_type: "movie",
    cefr_level: "C1",
    external_url: justWatchUrl("The Social Network"),
    genre_tag: "Movie",
    thumbnail_url: "https://image.tmdb.org/t/p/w300/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg",
    sort_order: 7,
  },
  {
    id: "ref-movie-speech",
    title: "The King's Speech",
    author_or_host: "Movie",
    media_type: "movie",
    cefr_level: "C1",
    external_url: justWatchUrl("The King's Speech"),
    genre_tag: "Movie",
    thumbnail_url: "https://image.tmdb.org/t/p/w500/pVNKXVQFukBaCz6ML7GH3kiPlQP.jpg",
    sort_order: 8,
  },
  {
    id: "ref-music-folklore",
    title: "folklore",
    author_or_host: "Taylor Swift",
    media_type: "music",
    cefr_level: null,
    external_url: spotifySearchUrl("folklore Taylor Swift"),
    genre_tag: "Music",
    thumbnail_url: "https://i.scdn.co/image/ab67616d00001e0295f754318336a07e85ec59bc",
    sort_order: 1,
  },
  {
    id: "ref-music-divide",
    title: "Divide",
    author_or_host: "Ed Sheeran",
    media_type: "music",
    cefr_level: null,
    external_url: spotifySearchUrl("Divide Ed Sheeran"),
    genre_tag: "Music",
    thumbnail_url: "https://i.scdn.co/image/ab67616d0000b273ba5db46f4b838ef6027e6f96",
    sort_order: 2,
  },
  {
    id: "ref-music-billie",
    title: "Happier Than Ever",
    author_or_host: "Billie Eilish",
    media_type: "music",
    cefr_level: null,
    external_url: spotifySearchUrl("Happier Than Ever Billie Eilish"),
    genre_tag: "Music",
    thumbnail_url: "https://i.scdn.co/image/ab67616d00001e022a038d3bf875d23e4aeaa84e",
    sort_order: 3,
  },
  {
    id: "ref-music-bruno",
    title: "24K Magic",
    author_or_host: "Bruno Mars",
    media_type: "music",
    cefr_level: null,
    external_url: spotifySearchUrl("24K Magic Bruno Mars"),
    genre_tag: "Music",
    thumbnail_url: "https://i.scdn.co/image/ab67616d00001e02232711f7d66a1e19e89e28c5",
    sort_order: 4,
  },
  {
    id: "ref-music-30",
    title: "30",
    author_or_host: "Adele",
    media_type: "music",
    cefr_level: null,
    external_url: spotifySearchUrl("30 Adele"),
    genre_tag: "Music",
    thumbnail_url: "https://i.scdn.co/image/ab67616d00001e02c6b577e4c4a6d326354a89f7",
    sort_order: 5,
  },
  {
    id: "ref-music-coldplay",
    title: "A Head Full of Dreams",
    author_or_host: "Coldplay",
    media_type: "music",
    cefr_level: null,
    external_url: spotifySearchUrl("A Head Full of Dreams Coldplay"),
    genre_tag: "Music",
    thumbnail_url: "https://i.scdn.co/image/ab67616d00001e028ff7c3580d429c8212b9a3b6",
    sort_order: 6,
  },
  {
    id: "ref-music-sara",
    title: "Amidst the Chaos",
    author_or_host: "Sara Bareilles",
    media_type: "music",
    cefr_level: null,
    external_url: spotifySearchUrl("Amidst the Chaos Sara Bareilles"),
    genre_tag: "Music",
    thumbnail_url: "https://i.scdn.co/image/ab67616d00001e0286164971ea2526a56f6cfe27",
    sort_order: 7,
  },
  {
    id: "ref-pod-daily",
    title: "The Daily",
    author_or_host: "NYT",
    media_type: "podcast",
    cefr_level: "B2",
    external_url: "https://www.nytimes.com/column/the-daily",
    genre_tag: "News",
    duration_label: "25 MIN",
    description: "A 25-minute news story, every weekday. Conversational, current, very American.",
    sort_order: 1,
  },
  {
    id: "ref-pod-built",
    title: "How I Built This",
    author_or_host: "NPR",
    media_type: "podcast",
    cefr_level: "B2",
    external_url: "https://www.npr.org/series/490248027/how-i-built-this",
    genre_tag: "Business",
    duration_label: "45 MIN",
    description:
      "Founders tell the real story of building their company. Business English in the wild.",
    sort_order: 2,
  },
  {
    id: "ref-pod-ted",
    title: "TED Talks Daily",
    author_or_host: "TED",
    media_type: "podcast",
    cefr_level: "B1-B2",
    external_url: "https://www.ted.com/podcasts/ted-talks-daily",
    genre_tag: "Ideas",
    duration_label: "15 MIN",
    description: "One powerful idea, clearly explained. Every accent, every topic.",
    sort_order: 3,
  },
  {
    id: "ref-pod-tal",
    title: "This American Life",
    author_or_host: "NPR",
    media_type: "podcast",
    cefr_level: "C1",
    external_url: "https://www.thisamericanlife.org/",
    genre_tag: "Storytelling",
    duration_label: "60 MIN",
    description: "Real stories of American life, told as radio essays. The gold standard.",
    sort_order: 4,
  },
  {
    id: "ref-pod-all-ears",
    title: "All Ears English",
    author_or_host: "All Ears",
    media_type: "podcast",
    cefr_level: "B1-B2",
    external_url: "https://www.allearsenglish.com/episodes/",
    genre_tag: "ESL",
    duration_label: "20 MIN",
    description: "Two American hosts. Conversational, warm, built specifically for learners.",
    sort_order: 5,
  },
  {
    id: "ref-pod-bbc",
    title: "6 Minute English",
    author_or_host: "BBC",
    media_type: "podcast",
    cefr_level: "A2-B1",
    external_url: "https://www.bbc.co.uk/learningenglish/english/features/6-minute-english",
    genre_tag: "BBC",
    duration_label: "6 MIN",
    description: "BBC. One topic, six minutes. Perfect for any commute.",
    sort_order: 6,
  },
  {
    id: "ref-pod-luke",
    title: "Luke's English Podcast",
    author_or_host: "Luke Thompson",
    media_type: "podcast",
    cefr_level: "B2-C1",
    external_url: "https://teacherluke.co.uk/",
    genre_tag: "ESL",
    duration_label: "40 MIN",
    description:
      "British comedian + qualified teacher. Hours of natural-paced English for learners.",
    sort_order: 7,
  },
  {
    id: "ref-pod-espresso",
    title: "Espresso English",
    author_or_host: "Espresso English",
    media_type: "podcast",
    cefr_level: "A2-B1",
    external_url: "https://www.espressoenglish.net/podcast/",
    genre_tag: "ESL",
    duration_label: "10 MIN",
    description: "Bite-sized American English lessons. Practical, clear, perfect for busy days.",
    sort_order: 8,
  },
  {
    id: "ref-book-mango",
    title: "The House on Mango Street",
    author_or_host: "Sandra Cisneros",
    media_type: "book",
    cefr_level: "B1",
    external_url: "https://www.amazon.com/dp/0679734775",
    genre_tag: "Book",
    thumbnail_url: "https://covers.openlibrary.org/b/isbn/0679734775-M.jpg",
    sort_order: 1,
  },
  {
    id: "ref-book-alchemist",
    title: "The Alchemist",
    author_or_host: "Paulo Coelho",
    media_type: "book",
    cefr_level: "B1",
    external_url: "https://www.amazon.com/dp/0061122416",
    genre_tag: "Book",
    thumbnail_url: "https://covers.openlibrary.org/b/isbn/0061122416-M.jpg",
    sort_order: 2,
  },
  {
    id: "ref-book-morrie",
    title: "Tuesdays with Morrie",
    author_or_host: "Mitch Albom",
    media_type: "book",
    cefr_level: "B1",
    external_url: "https://www.amazon.com/dp/076790592X",
    genre_tag: "Book",
    thumbnail_url: "https://covers.openlibrary.org/b/isbn/076790592X-M.jpg",
    sort_order: 3,
  },
  {
    id: "ref-book-curious",
    title: "The Curious Incident",
    author_or_host: "Mark Haddon",
    media_type: "book",
    cefr_level: "B1-B2",
    external_url: "https://www.amazon.com/dp/1400032717",
    genre_tag: "Book",
    thumbnail_url: "https://covers.openlibrary.org/b/isbn/1400032717-M.jpg",
    sort_order: 4,
  },
  {
    id: "ref-book-stars",
    title: "The Fault in Our Stars",
    author_or_host: "John Green",
    media_type: "book",
    cefr_level: "B1-B2",
    external_url: "https://www.amazon.com/dp/014242417X",
    genre_tag: "Book",
    thumbnail_url: "https://covers.openlibrary.org/b/isbn/014242417X-M.jpg",
    sort_order: 5,
  },
  {
    id: "ref-book-atomic",
    title: "Atomic Habits",
    author_or_host: "James Clear",
    media_type: "book",
    cefr_level: "B2",
    external_url: "https://www.amazon.com/dp/0735211299",
    genre_tag: "Book",
    thumbnail_url: "https://covers.openlibrary.org/b/isbn/0735211299-M.jpg",
    sort_order: 6,
  },
  {
    id: "ref-book-educated",
    title: "Educated",
    author_or_host: "Tara Westover",
    media_type: "book",
    cefr_level: "C1",
    external_url: "https://www.amazon.com/dp/0399590501",
    genre_tag: "Book",
    thumbnail_url: "https://covers.openlibrary.org/b/isbn/0399590501-M.jpg",
    sort_order: 7,
  },
  {
    id: "ref-src-news",
    title: "Same news, 3 reading levels",
    author_or_host: "News in Levels",
    media_type: "reading_source",
    cefr_level: null,
    external_url: "https://www.newsinlevels.com",
    genre_tag: "News in Levels",
    description: "Read any story at your level, then level up.",
    sort_order: 1,
  },
  {
    id: "ref-src-bbc",
    title: "Daily English lessons",
    author_or_host: "BBC Learning English",
    media_type: "reading_source",
    cefr_level: null,
    external_url: "https://www.bbc.co.uk/learningenglish",
    genre_tag: "BBC Learning English",
    description: "Free, structured, updated constantly. All levels.",
    sort_order: 2,
  },
  {
    id: "ref-src-atlantic",
    title: "Long-form journalism",
    author_or_host: "The Atlantic",
    media_type: "reading_source",
    cefr_level: "C1+",
    external_url: "https://www.theatlantic.com",
    genre_tag: "The Atlantic",
    description: "In-depth essays on culture and ideas. Best for C1+.",
    sort_order: 3,
  },
  {
    id: "ref-src-npr",
    title: "Text + audio immersion",
    author_or_host: "NPR",
    media_type: "reading_source",
    cefr_level: null,
    external_url: "https://www.npr.org",
    genre_tag: "NPR",
    description: "Read the article and listen to it. Full immersion.",
    sort_order: 4,
  },
  {
    id: "ref-src-medium",
    title: "Modern essays",
    author_or_host: "Medium",
    media_type: "reading_source",
    cefr_level: null,
    external_url: "https://www.medium.com",
    genre_tag: "Medium",
    description: "Endless modern writing on every topic.",
    sort_order: 5,
  },
  {
    id: "ref-play-commute",
    title: "For your commute",
    author_or_host: "Playlist",
    media_type: "playlist",
    cefr_level: null,
    external_url: "#",
    genre_tag: "car",
    description:
      "Short-form content, 5-30 min. Podcasts, music, and news for the in-between moments.",
    duration_label: "6 picks ->",
    sort_order: 1,
  },
  {
    id: "ref-play-career",
    title: "For your career",
    author_or_host: "Playlist",
    media_type: "playlist",
    cefr_level: null,
    external_url: "#",
    genre_tag: "work",
    description:
      "Business books, founder podcasts, industry news. Vocabulary you'll actually use at work.",
    duration_label: "6 picks ->",
    sort_order: 2,
  },
  {
    id: "ref-play-unwind",
    title: "To unwind in English",
    author_or_host: "Playlist",
    media_type: "playlist",
    cefr_level: null,
    external_url: "#",
    genre_tag: "moon",
    description:
      "Slow shows, gentle podcasts. For when your brain is tired but still wants exposure.",
    duration_label: "6 picks ->",
    sort_order: 3,
  },
  {
    id: "ref-play-laugh",
    title: "To laugh in English",
    author_or_host: "Playlist",
    media_type: "playlist",
    cefr_level: null,
    external_url: "#",
    genre_tag: "laugh",
    description:
      "Comedy shows and funny podcasts. Humor is one of the fastest ways to feel at home.",
    duration_label: "5 picks ->",
    sort_order: 4,
  },
  {
    id: "ref-play-bold",
    title: "Bold conversations",
    author_or_host: "Playlist",
    media_type: "playlist",
    cefr_level: null,
    external_url: "#",
    genre_tag: "fire",
    description: "Faster, denser, harder. For when you're ready to stretch.",
    duration_label: "6 picks ->",
    sort_order: 5,
  },
];

export function mergeReferenceContent<T extends ContentLibraryItem>(content: T[]): T[] {
  const seen = new Set(
    referenceContentItems.map((item) => `${item.media_type}:${item.title}`.toLowerCase()),
  );
  return [
    ...(referenceContentItems as T[]),
    ...content.filter((item) => !seen.has(`${item.media_type}:${item.title}`.toLowerCase())),
  ];
}

const playlistSelections: Record<string, string[]> = {
  car: ["The Daily", "6 Minute English", "TED Talks Daily", "Espresso English", "News in Levels"],
  work: [
    "How I Built This",
    "Atomic Habits",
    "The Social Network",
    "The Atlantic",
    "TED Talks Daily",
    "NPR",
  ],
  moon: [
    "Friends",
    "Modern Family",
    "Emily in Paris",
    "Little Women",
    "All Ears English",
    "folklore",
  ],
  laugh: ["The Office", "Brooklyn Nine-Nine", "Ted Lasso", "Friends", "Luke's English Podcast"],
  fire: [
    "This American Life",
    "The Atlantic",
    "The Social Network",
    "The King's Speech",
    "Educated",
    "TED Talks Daily",
  ],
};

function playlistMatches(item: ContentLibraryItem, target: string) {
  const haystack = [
    item.title,
    item.author_or_host,
    item.genre_tag,
    item.playlist_tag,
    item.media_type,
  ]
    .filter(Boolean)
    .map((value) => String(value).toLowerCase());

  return haystack.includes(target.toLowerCase());
}

export function playlistItemsFor<T extends ContentLibraryItem>(playlist: T, items: T[]) {
  const playlistKey = playlist.genre_tag ?? playlist.playlist_tag ?? playlist.id;
  const selections = playlistSelections[playlistKey] ?? [];
  const selectionOrder = new Map(selections.map((title, index) => [title.toLowerCase(), index]));

  return items
    .filter((item) => item.media_type !== "playlist")
    .filter((item) => {
      if (item.playlist_tag === playlistKey || item.genre_tag === playlistKey) return true;
      return selections.some((target) => playlistMatches(item, target));
    })
    .sort((a, b) => {
      const aIndex =
        selectionOrder.get(a.title.toLowerCase()) ??
        selectionOrder.get((a.author_or_host ?? "").toLowerCase()) ??
        999 + (a.sort_order ?? 0);
      const bIndex =
        selectionOrder.get(b.title.toLowerCase()) ??
        selectionOrder.get((b.author_or_host ?? "").toLowerCase()) ??
        999 + (b.sort_order ?? 0);
      return aIndex - bIndex;
    })
    .slice(0, 8);
}
